const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.Tween,
		C3.Behaviors.Timer,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Plugins.Particles,
		C3.Plugins.Spritefont2,
		C3.Behaviors.MoveTo,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.ScrollToObject,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.SetEffectParameter,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.AddFilterEffect,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.System.Exps.scrollx,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.EightDir.Exps.VectorY,
		C3.Behaviors.EightDir.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.max,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.TiledBg.Exps.BBoxBottom,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.EightDir.Acts.SetSpeed,
		C3.Plugins.System.Exps.min,
		C3.Behaviors.EightDir.Exps.Speed,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.ForEach,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgba255,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetOpacity
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Keyboard: 0},
	{underwater: 0},
	{acceleration: 0},
	{speedReduction: 0},
	{oxyDepletionConst: 0},
	{oxyRepletionConst: 0},
	{"8Direction": 0},
	{Tween: 0},
	{Timer: 0},
	{Player: 0},
	{Solid: 0},
	{Tilemap: 0},
	{Oxygen: 0},
	{PlayerNose: 0},
	{Water: 0},
	{fullOfLIfe: 0},
	{Coral: 0},
	{Seeds: 0},
	{LogicalSeeds: 0},
	{OxygenBar: 0},
	{OxygenAmount: 0},
	{Background: 0},
	{WaterMask: 0},
	{Fader: 0},
	{TextTutorial: 0},
	{TextCoralsSaved: 0},
	{IconCoralsSaved: 0},
	{TextGameOver: 0},
	{piranhaID: 0},
	{nextWpt: 0},
	{wptCount: 0},
	{MoveTo: 0},
	{Piranha: 0},
	{wptID: 0},
	{mirrorPiranha: 0},
	{PiranhaWpt: 0},
	{BubbleParticles: 0},
	{Touch: 0},
	{StartLayout: 0},
	{Text: 0},
	{TiledBackground: 0},
	{Sprite: 0},
	{TurtleTidyUp: 0},
	{TutorialText: 0},
	{inputFocus: 0},
	{CoralsSaved: 0},
	{TimerActive: 0},
	{DelayCounter: 0},
	{anim: 0},
	{fadeTime: 0},
	{HorizontalAxis: 0},
	{VerticalAxis: 0},
	{status: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Player: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Oxygen: class extends self.ITiledBackgroundInstance {},
	PlayerNose: class extends self.ISpriteInstance {},
	Water: class extends self.ITiledBackgroundInstance {},
	Coral: class extends self.ISpriteInstance {},
	Seeds: class extends self.IParticlesInstance {},
	LogicalSeeds: class extends self.ITiledBackgroundInstance {},
	OxygenBar: class extends self.ISpriteInstance {},
	OxygenAmount: class extends self.ITiledBackgroundInstance {},
	Background: class extends self.ISpriteInstance {},
	WaterMask: class extends self.ISpriteInstance {},
	Fader: class extends self.ITiledBackgroundInstance {},
	TextTutorial: class extends self.ISpriteFontInstance {},
	TextCoralsSaved: class extends self.ISpriteFontInstance {},
	IconCoralsSaved: class extends self.ISpriteInstance {},
	TextGameOver: class extends self.ISpriteFontInstance {},
	Piranha: class extends self.ISpriteInstance {},
	PiranhaWpt: class extends self.ISpriteInstance {},
	BubbleParticles: class extends self.IParticlesInstance {},
	Timer: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	StartLayout: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TurtleTidyUp: class extends self.ITextInstance {},
	TutorialText: class extends self.ITextInstance {}
}